/* Base de datos de Flores de Bach y Esencias de California
   Cada flor tiene: id, nombre, origen (Bach/California), categoria emocional,
   descripcion corta y un array de sintomas/palabras clave para el recomendador. */

const FLORES_DB = [
  // ===================== FLORES DE BACH (38) =====================
  { id: 'agrimony', nombre: 'Agrimony (Agrimonia)', origen: 'Bach', categoria: 'Ansiedad y preocupación',
    descripcion: 'Para quienes ocultan su angustia detrás de una máscara de alegría y buen humor.',
    sintomas: ['oculta sus problemas', 'finge estar bien', 'evita conflictos', 'ansiedad oculta', 'busca aprobación', 'miedo a aburrir a otros con sus penas'] },
  { id: 'aspen', nombre: 'Aspen (Álamo temblón)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para miedos e inquietudes de origen desconocido, presentimientos vagos.',
    sintomas: ['miedo sin causa aparente', 'presentimientos', 'ansiedad nocturna', 'pesadillas', 'inquietud difusa', 'aprensión'] },
  { id: 'beech', nombre: 'Beech (Haya)', origen: 'Bach', categoria: 'Sensibilidad excesiva a las opiniones',
    descripcion: 'Para la intolerancia, la crítica excesiva y la falta de flexibilidad hacia los demás.',
    sintomas: ['intolerancia', 'critica a los demás', 'perfeccionismo con otros', 'rigidez', 'poca empatía', 'irritabilidad ante errores ajenos'] },
  { id: 'centaury', nombre: 'Centaury (Centaura)', origen: 'Bach', categoria: 'Falta de voluntad',
    descripcion: 'Para quienes no saben decir que no y se someten a la voluntad de otros.',
    sintomas: ['no puede decir que no', 'se somete a otros', 'falta de límites', 'complacencia excesiva', 'se deja explotar', 'baja autoafirmación'] },
  { id: 'cerato', nombre: 'Cerato (Ceratostigma)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para quienes dudan de su propio criterio y buscan constantemente la opinión de otros.',
    sintomas: ['duda de sí mismo', 'pide muchos consejos', 'inseguridad en decisiones', 'necesita validación externa', 'desconfía de su intuición'] },
  { id: 'cherry-plum', nombre: 'Cherry Plum (Ciruelo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el miedo a perder el control, a hacer algo impulsivo o dañino.',
    sintomas: ['miedo a perder el control', 'pensamientos impulsivos', 'miedo a hacerse daño', 'tensión extrema', 'explosiones de ira', 'colapso nervioso'] },
  { id: 'chestnut-bud', nombre: 'Chestnut Bud (Castaño de yemas)', origen: 'Bach', categoria: 'Falta de interés / aprendizaje',
    descripcion: 'Para quienes repiten los mismos errores sin aprender de la experiencia.',
    sintomas: ['repite los mismos errores', 'no aprende de la experiencia', 'distraído', 'falta de observación', 'apresurado'] },
  { id: 'chicory', nombre: 'Chicory (Achicoria)', origen: 'Bach', categoria: 'Sobreprotección / posesividad',
    descripcion: 'Para el amor posesivo, exigente, que necesita sentirse necesitado.',
    sintomas: ['posesivo', 'exigente con el cariño', 'manipulador emocional', 'necesita ser el centro de atención', 'autocompasión', 'controlador con los seres queridos'] },
  { id: 'clematis', nombre: 'Clematis (Clemátide)', origen: 'Bach', categoria: 'Falta de interés en el presente',
    descripcion: 'Para quienes viven en las nubes, soñadores, desconectados del presente.',
    sintomas: ['soñador', 'desconectado del presente', 'falta de concentración', 'somnolencia', 'evasión de la realidad', 'poca vitalidad'] },
  { id: 'crab-apple', nombre: 'Crab Apple (Manzano silvestre)', origen: 'Bach', categoria: 'Desánimo / purificación',
    descripcion: 'La flor de la limpieza, para sentimientos de suciedad física o mental, vergüenza corporal.',
    sintomas: ['sensación de suciedad', 'vergüenza del cuerpo', 'obsesión por los detalles', 'autocrítica física', 'necesidad de depurar', 'baja autoestima corporal'] },
  { id: 'elm', nombre: 'Elm (Olmo)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para quienes se sienten abrumados por la responsabilidad, agotados momentáneamente.',
    sintomas: ['abrumado por responsabilidades', 'agotamiento puntual', 'duda de su capacidad', 'sobrecarga laboral', 'estrés por exceso de tareas'] },
  { id: 'gentian', nombre: 'Gentian (Genciana)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el desánimo ante contratiempos, pesimismo con causa conocida.',
    sintomas: ['desánimo ante contratiempos', 'pesimismo', 'se rinde fácilmente', 'dudas tras un fracaso', 'desmotivación'] },
  { id: 'gorse', nombre: 'Gorse (Aulaga)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la desesperanza profunda, sensación de que nada puede ayudar.',
    sintomas: ['desesperanza', 'siente que nada ayudará', 'resignación', 'pesimismo extremo', 'falta de fe en la mejora'] },
  { id: 'heather', nombre: 'Heather (Brezo)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para quienes necesitan hablar constantemente de sí mismos y temen la soledad.',
    sintomas: ['habla solo de sí mismo', 'necesita compañía constante', 'miedo a la soledad', 'busca atención', 'ansiedad al estar solo'] },
  { id: 'holly', nombre: 'Holly (Acebo)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la ira, los celos, la envidia y la desconfianza.',
    sintomas: ['celos', 'envidia', 'ira', 'desconfianza', 'irritabilidad', 'rencor', 'agresividad'] },
  { id: 'honeysuckle', nombre: 'Honeysuckle (Madreselva)', origen: 'Bach', categoria: 'Falta de interés en el presente',
    descripcion: 'Para vivir anclado en recuerdos y añoranzas del pasado.',
    sintomas: ['vive en el pasado', 'nostalgia', 'añoranza', 'dificultad para avanzar', 'apego a recuerdos'] },
  { id: 'hornbeam', nombre: 'Hornbeam (Carpe)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la fatiga mental, el cansancio al pensar en las tareas diarias.',
    sintomas: ['cansancio mental', 'pereza matutina', 'falta de energía para empezar', 'agotamiento por rutina', 'procrastinación'] },
  { id: 'impatiens', nombre: 'Impatiens (Impaciencia)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para la impaciencia, la irritabilidad y las prisas.',
    sintomas: ['impaciencia', 'irritabilidad', 'prisa constante', 'tensión muscular', 'quiere hacer todo rápido', 'poca tolerancia a la lentitud ajena'] },
  { id: 'larch', nombre: 'Larch (Alerce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la falta de confianza en uno mismo, sensación de inferioridad.',
    sintomas: ['falta de confianza', 'sensación de inferioridad', 'miedo al fracaso', 'no se anima a intentar', 'autoestima baja'] },
  { id: 'mimulus', nombre: 'Mimulus (Mímulo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para miedos conocidos y concretos: a la oscuridad, a hablar en público, etc.',
    sintomas: ['miedo concreto', 'timidez', 'miedo a hablar en público', 'miedo a enfermedades', 'temores específicos', 'nerviosismo ante lo cotidiano'] },
  { id: 'mustard', nombre: 'Mustard (Mostaza)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la tristeza profunda que llega sin motivo aparente, como una nube negra.',
    sintomas: ['tristeza sin causa', 'melancolía', 'nube negra', 'depresión pasajera', 'cambios de humor repentinos'] },
  { id: 'oak', nombre: 'Oak (Roble)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para quienes luchan sin descanso a pesar del agotamiento, sin pedir ayuda.',
    sintomas: ['exceso de responsabilidad', 'no pide ayuda', 'lucha sin descanso', 'agotamiento por exigencia propia', 'perseverancia extrema'] },
  { id: 'olive', nombre: 'Olive (Olivo)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el agotamiento físico y mental extremo, tras un esfuerzo prolongado.',
    sintomas: ['agotamiento extremo', 'fatiga física', 'falta total de energía', 'convalecencia', 'exhausto tras esfuerzo prolongado'] },
  { id: 'pine', nombre: 'Pine (Pino)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la culpa excesiva, el autorreproche y el sentimiento de no merecer.',
    sintomas: ['culpa excesiva', 'autorreproche', 'se disculpa constantemente', 'no se siente merecedor', 'sentimiento de culpa ajena'] },
  { id: 'red-chestnut', nombre: 'Red Chestnut (Castaño rojo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el miedo y la preocupación excesiva por la seguridad de los seres queridos.',
    sintomas: ['preocupación excesiva por otros', 'miedo por la familia', 'anticipa desgracias ajenas', 'sobreprotección ansiosa'] },
  { id: 'rock-rose', nombre: 'Rock Rose (Heliantemo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el terror y el pánico agudo, situaciones de emergencia.',
    sintomas: ['terror', 'pánico', 'miedo extremo', 'pesadillas terroríficas', 'situación de emergencia', 'alarma'] },
  { id: 'rock-water', nombre: 'Rock Water (Agua de roca)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la rigidez consigo mismo, el autoexigencia extrema y el perfeccionismo.',
    sintomas: ['autoexigencia extrema', 'rigidez consigo mismo', 'perfeccionismo personal', 'autodisciplina excesiva', 'poca flexibilidad propia'] },
  { id: 'scleranthus', nombre: 'Scleranthus (Centinodia)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para la indecisión entre dos opciones y los cambios de humor bruscos.',
    sintomas: ['indecisión', 'cambios de humor bruscos', 'duda entre dos opciones', 'inestabilidad emocional', 'falta de equilibrio interior'] },
  { id: 'star-of-bethlehem', nombre: 'Star of Bethlehem (Estrella de Belén)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el shock, el trauma y las consecuencias de malas noticias.',
    sintomas: ['shock', 'trauma', 'duelo', 'mala noticia reciente', 'conmoción emocional', 'secuelas de un accidente'] },
  { id: 'sweet-chestnut', nombre: 'Sweet Chestnut (Castaño dulce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la angustia extrema, sensación de haber llegado al límite de lo soportable.',
    sintomas: ['angustia extrema', 'límite de lo soportable', 'desesperación profunda', 'sensación de vacío total', 'noche oscura del alma'] },
  { id: 'vervain', nombre: 'Vervain (Verbena)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para el exceso de entusiasmo, fanatismo y tensión por querer convencer a otros.',
    sintomas: ['exceso de entusiasmo', 'fanatismo', 'quiere convencer a otros', 'tensión nerviosa', 'sobreesfuerzo por una causa', 'estrés por ideales'] },
  { id: 'vine', nombre: 'Vine (Vid)', origen: 'Bach', categoria: 'Sobreprotección',
    descripcion: 'Para la dominancia, el autoritarismo y la necesidad de controlar a otros.',
    sintomas: ['autoritario', 'dominante', 'necesita controlar a otros', 'inflexible con subordinados', 'ambición de poder'] },
  { id: 'walnut', nombre: 'Walnut (Nogal)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la protección en momentos de cambio y transición, para romper vínculos limitantes.',
    sintomas: ['dificultad con los cambios', 'transición vital', 'mudanza', 'nueva etapa', 'influencias externas', 'dejarse influenciar demasiado'] },
  { id: 'water-violet', nombre: 'Water Violet (Violeta de agua)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para quienes se aíslan por orgullo, prefieren la soledad y parecen distantes.',
    sintomas: ['aislamiento voluntario', 'orgullo', 'distante', 'prefiere estar solo', 'dificultad para pedir ayuda', 'reservado'] },
  { id: 'white-chestnut', nombre: 'White Chestnut (Castaño de indias)', origen: 'Bach', categoria: 'Falta de interés',
    descripcion: 'Para los pensamientos repetitivos e incontrolables, la mente que no descansa.',
    sintomas: ['pensamientos repetitivos', 'mente que no para', 'insomnio por pensar', 'rumiación mental', 'preocupaciones circulares'] },
  { id: 'wild-oat', nombre: 'Wild Oat (Avena silvestre)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para la falta de dirección vital, no saber qué camino profesional o de vida seguir.',
    sintomas: ['falta de rumbo', 'no sabe qué hacer con su vida', 'indecisión vocacional', 'insatisfacción profesional', 'búsqueda de propósito'] },
  { id: 'wild-rose', nombre: 'Wild Rose (Rosa silvestre)', origen: 'Bach', categoria: 'Falta de interés',
    descripcion: 'Para la apatía y resignación, dejarse llevar sin motivación por la vida.',
    sintomas: ['apatía', 'resignación', 'falta de motivación', 'dejadez', 'monotonía sin queja', 'indiferencia'] },
  { id: 'willow', nombre: 'Willow (Sauce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el resentimiento, la amargura y sentirse víctima de las circunstancias.',
    sintomas: ['resentimiento', 'amargura', 'sentirse víctima', 'autocompasión', 'rencor por injusticias', 'queja constante'] },
  { id: 'rescue-remedy', nombre: 'Rescue Remedy (Flor de rescate)', origen: 'Bach', categoria: 'Emergencia',
    descripcion: 'Combinación de emergencia para crisis agudas de estrés, pánico o shock puntual.',
    sintomas: ['crisis aguda', 'emergencia emocional', 'shock puntual', 'ataque de pánico', 'antes de un examen o evento estresante'] },

  // ===================== ESENCIAS DE CALIFORNIA (Sistema FES — repertorio propio) =====================
  { id: 'black-eyed-susan', nombre: 'Black-Eyed Susan (Ojo de buey)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Ilumina las partes oscuras de la psique que la persona se niega a ver, ayudando a integrar traumas y secretos reprimidos. Relación con Bach: Agrimony.',
    sintomas: ['reprime traumas', 'niega el malestar', 'amnesia emocional', 'terapia estancada', 'evita mirar sus emociones', 'negación sistemática'] },
  { id: 'borage', nombre: 'Borage (Borraja)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'La "flor del coraje": infunde optimismo y ligereza cuando el corazón está abrumado por la pena o el desánimo profundo. Relación con Bach: Gentian + Gorse.',
    sintomas: ['desánimo profundo', 'tristeza que pesa en el pecho', 'duelo', 'convalecencia larga', 'falta de coraje ante la adversidad'] },
  { id: 'chamomile', nombre: 'Chamomile (Manzanilla)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Tranquilizante emocional que libera la tensión del plexo solar y equilibra los altibajos de ánimo. Relación con Bach: Impatiens + Cherry Plum.',
    sintomas: ['irritabilidad', 'altibajos de humor', 'insomnio nervioso', 'estrés digestivo', 'niños inquietos'] },
  { id: 'evening-primrose', nombre: 'Evening Primrose (Prímula de tarde)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Sana heridas de rechazo prenatal o de la primera infancia, restaurando la capacidad de dar y recibir amor. Relación con Bach: Chicory + Honeysuckle.',
    sintomas: ['sensación de no ser deseado', 'frialdad emocional', 'soledad profunda', 'problemas de apego', 'adicciones por carencia afectiva'] },
  { id: 'mariposa-lily', nombre: 'Mariposa Lily (Azucena mariposa)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Esencia maestra del vínculo materno: nutre el alma que no recibió suficiente cuidado en la infancia. Relación con Bach: Chicory.',
    sintomas: ['herida de abandono materno', 'desapego afectivo', 'frialdad', 'trastornos alimentarios', 'dificultad para nutrir emocionalmente'] },
  { id: 'tansy', nombre: 'Tansy (Tanaceto)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Para el autosabotaje y la procrastinación inconsciente: ayuda a alinear la voluntad con la acción. Relación con Bach: Wild Rose + Scleranthus.',
    sintomas: ['autosabotaje', 'procrastinación', 'parálisis activa', 'proyectos inacabados', 'quiere pero no puede'] },
  { id: 'bleeding-heart', nombre: 'Bleeding Heart (Corazón de la virgen)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Para el dolor de ruptura amorosa y el apego tóxico: enseña a amar en libertad y sin posesión. Relación con Bach: Chicory + Red Chestnut + Honeysuckle.',
    sintomas: ['codependencia', 'dolor por ruptura', 'posesividad amorosa', 'duelo amoroso agudo', 'obsesión amorosa'] },
  { id: 'fuchsia', nombre: 'Fuchsia (Fucsia)', origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Desbloquea emociones intensas reprimidas y enmascaradas con comportamientos histriónicos. Relación con Bach: Agrimony + Cherry Plum + Heather.',
    sintomas: ['emociones enmascaradas', 'histeria', 'reacciones psicosomáticas', 'llanto falso', 'bloqueos de ira'] },
  { id: 'golden-ear-drops', nombre: "Golden Ear Drops (Gotas doradas)", origen: 'California', categoria: 'Vida Afectiva',
    descripcion: 'Facilita el contacto con recuerdos dolorosos de la infancia reprimidos, permitiendo el llanto liberador. Relación con Bach: Honeysuckle + Star of Bethlehem.',
    sintomas: ['recuerdos traumáticos reprimidos', 'tristeza infantil bloqueada', 'amnesia emocional de la niñez', 'bloqueos en terapia regresiva', 'duelo no procesado de la infancia'] },

  { id: 'hibiscus', nombre: 'Hibiscus (Hibisco)', origen: 'California', categoria: 'Vida Sexual',
    descripcion: 'Restaura la calidez y el placer en la sexualidad, disolviendo la disociación entre el corazón y el cuerpo. Relación con Bach: Pine + Larch + Agrimony.',
    sintomas: ['frigidez psicoemocional', 'disociación sexual', 'falta de libido', 'trauma sexual', 'falta de calidez corporal'] },

  { id: 'aloe-vera', nombre: 'Aloe Vera (Sábila)', origen: 'California', categoria: 'Vida Energética',
    descripcion: 'Para el burnout creativo o laboral: restaura el equilibrio entre el dar creativo y el recibir vital. Relación con Bach: Olive + Oak.',
    sintomas: ['burnout', 'agotamiento por exceso de ambición', 'fatiga crónica', 'estrés agudo', 'sensación de estar quemado'] },
  { id: 'arnica', nombre: 'Arnica', origen: 'California', categoria: 'Vida Energética',
    descripcion: 'Para traumas y shocks: ayuda al alma a regresar al cuerpo tras un accidente, cirugía o impacto emocional. Relación con Bach: Star of Bethlehem + Rescue Remedy.',
    sintomas: ['disociación post-trauma', 'shock emocional', 'no estar en el cuerpo', 'secuelas de accidente', 'trauma físico o emocional súbito'] },
  { id: 'dandelion', nombre: 'Dandelion (Diente de león)', origen: 'California', categoria: 'Vida Energética',
    descripcion: 'Libera la tensión muscular crónica y el estrés acumulado por el exceso de esfuerzo e intensidad. Relación con Bach: Rock Water + Oak + Vervain.',
    sintomas: ['tensión muscular crónica', 'contracturas', 'hiperactividad tensa', 'fuerza su cuerpo más allá del límite', 'dolor muscular por estrés'] },
  { id: 'echinacea', nombre: 'Echinacea (Equinácea)', origen: 'California', categoria: 'Vida Energética',
    descripcion: 'Restaura la dignidad y la integridad del yo tras humillaciones, abusos o traumas devastadores. Relación con Bach: Star of Bethlehem + Centaury + Oak.',
    sintomas: ['trauma por abuso', 'fragilidad extrema', 'crisis de identidad', 'secuelas de humillación', 'sistema inmune débil'] },
  { id: 'lavender', nombre: 'Lavender (Lavanda)', origen: 'California', categoria: 'Vida Energética',
    descripcion: 'Para la hipersensibilidad nerviosa: aquieta la mente sobreestimulada de las personas altamente sensibles (PAS). Relación con Bach: White Chestnut + Impatiens + Vervain.',
    sintomas: ['hipersensibilidad', 'sobreestimulación nerviosa', 'insomnio', 'cefaleas por tensión', 'agotamiento por exceso de estímulos'] },

  { id: 'angelica', nombre: 'Angelica (Angélica)', origen: 'California', categoria: 'Vida Espiritual',
    descripcion: 'Brinda protección y guía espiritual, especialmente en momentos de umbral o crisis existencial. Relación con Bach: Aspen + Walnut + Rock Rose.',
    sintomas: ['desamparo espiritual', 'miedo a fuerzas desconocidas', 'aislamiento cósmico', 'crisis de fe', 'necesita sentirse guiado'] },
  { id: 'lotus', nombre: 'Lotus (Flor de loto)', origen: 'California', categoria: 'Vida Espiritual',
    descripcion: 'Integra todas las dimensiones del ser con humildad, evitando el orgullo espiritual y el fanatismo. Relación con Bach: Vervain + Water Violet + Rock Water.',
    sintomas: ['orgullo espiritual', 'fanatismo', 'desconexión de la realidad', 'mente dispersa en meditación', 'desequilibrios energéticos'] },
  { id: 'pansy', nombre: 'Pansy (Pensamiento)', origen: 'California', categoria: 'Vida Espiritual',
    descripcion: 'Cultiva la conciencia de la belleza y la percepción sutil, como puerta hacia lo divino en lo cotidiano. Relación con Bach: Mimulus + Clematis + Cerato.',
    sintomas: ['amargura', 'ceguera ante la belleza', 'hipersensibilidad agotadora', 'tristeza por la crudeza del mundo', 'falta de asombro'] },
  { id: 'sage', nombre: 'Sage (Salvia)', origen: 'California', categoria: 'Vida Espiritual',
    descripcion: 'Integra las experiencias de vida en sabiduría profunda, honrando el viaje del alma en las transiciones mayores. Relación con Bach: Willow + Wild Oat + Oak.',
    sintomas: ['amargura por el pasado', 'falta de sentido', 'crisis de mediana edad', 'sensación de vida desperdiciada', 'dificultad con el envejecimiento'] },
  { id: 'saint-johns-wort', nombre: "Saint John's Wort (Hipérico)", origen: 'California', categoria: 'Vida Espiritual',
    descripcion: '"Escudo de luz" que protege a personas psíquicamente muy abiertas y ayuda con pesadillas y depresión estacional. Relación con Bach: Aspen + Mimulus.',
    sintomas: ['vulnerabilidad psíquica', 'miedo nocturno', 'pesadillas', 'terrores nocturnos', 'depresión estacional', 'sensibilidad a la luz'] },

  { id: 'blackberry', nombre: 'Blackberry (Zarzamora)', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Puente entre la visión y la acción: ayuda a manifestar las ideas en la realidad física. Relación con Bach: Wild Oat + Larch + Clematis.',
    sintomas: ['procrastinación', 'sueños sin acción', 'incapacidad de concretar', 'parálisis por análisis', 'grandes proyectos que no se concretan'] },
  { id: 'cayenne', nombre: 'Cayenne (Cayena)', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Catalizador de cambio: aporta el impulso ardiente necesario para romper la inercia y la complacencia. Relación con Bach: Wild Rose + Hornbeam + Walnut.',
    sintomas: ['estancamiento crónico', 'autocomplacencia', 'resistencia al cambio', 'letargo vital', 'necesita un salto urgente'] },
  { id: 'cosmos', nombre: 'Cosmos', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Organiza los pensamientos dispersos en una expresión coherente y fluida al hablar o escribir. Relación con Bach: White Chestnut + Vervain + Cerato.',
    sintomas: ['pensamiento abrumado', 'comunicación confusa', 'desorden mental al hablar', 'verborragia confusa', 'exceso de ideas simultáneas'] },
  { id: 'madia', nombre: 'Madia', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Esencia del enfoque y la concentración unipuntual, para vencer la distracción y la dispersión mental. Relación con Bach: Clematis + Scleranthus + Chestnut Bud.',
    sintomas: ['dispersión mental', 'distracción fácil', 'mente vaga', 'bajo rendimiento por desatención', 'dificultad para concentrarse'] },
  { id: 'peppermint', nombre: 'Peppermint (Menta piperina)', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Revitaliza la mente y disipa la neblina cognitiva producto del cansancio por estudio o trabajo mental. Relación con Bach: Hornbeam + White Chestnut.',
    sintomas: ['neblina mental', 'letargo cerebral', 'mente embotada', 'cansancio intelectual', 'somnolencia al estudiar'] },
  { id: 'shasta-daisy', nombre: 'Shasta Daisy (Margarita Shasta)', origen: 'California', categoria: 'Vida Creativa y de Aprendizaje',
    descripcion: 'Integra fragmentos de información dispersos en un todo coherente; ideal para quien se pierde en los detalles. Relación con Bach: Scleranthus + White Chestnut + Cerato.',
    sintomas: ['fragmentación intelectual', 'obsesión por el detalle', 'dificultad para sintetizar', 'bloqueo al redactar', 'no ve el panorama general'] },

  { id: 'garlic', nombre: 'Garlic (Ajo)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Gran protector psíquico que disipa el miedo y la vulnerabilidad ante influencias negativas del entorno. Relación con Bach: Mimulus + Aspen + Walnut.',
    sintomas: ['vulnerabilidad a influencias ajenas', 'miedos crónicos', 'sensación de ser parasitado por otros', 'inmunidad débil', 'fragilidad ante el entorno'] },
  { id: 'golden-yarrow', nombre: 'Golden Yarrow (Milenrama dorada)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Escudo solar que permite la participación social sin perder la individualidad interior. Relación con Bach: Centaury + Mimulus + Walnut.',
    sintomas: ['hipersensibilidad al público', 'agotamiento social', 'fobia a hablar en público', 'ansiedad de exposición', 'se siente drenado por la mirada ajena'] },
  { id: 'mallow', nombre: 'Mallow (Malva)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Cultiva la calidez social y supera las barreras afectivas producidas por el miedo al rechazo. Relación con Bach: Water Violet + Mimulus.',
    sintomas: ['aislamiento', 'frialdad social', 'miedo al rechazo', 'dificultad para hacer amigos', 'timidez social'] },
  { id: 'pink-yarrow', nombre: 'Pink Yarrow (Milenrama rosada)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Establece límites emocionales saludables para personas con empatía excesiva que raya en la codependencia. Relación con Bach: Centaury + Red Chestnut.',
    sintomas: ['fusión sentimental', 'absorción del dolor ajeno', 'codependencia', 'burnout del cuidador', 'agotamiento empático'] },
  { id: 'red-clover', nombre: 'Red Clover (Trébol rojo)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Calma el pánico colectivo y la histeria social, ayudando a mantener el centro individual en las crisis grupales. Relación con Bach: Rock Rose + Cherry Plum + Rescue Remedy.',
    sintomas: ['contagio emocional de pánico', 'histeria colectiva', 'miedo grupal', 'pánico en masa', 'pierde la calma ante el caos social'] },
  { id: 'snapdragon', nombre: 'Snapdragon (Boca de dragón)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Canaliza la agresividad verbal y la libido reprimida, transformando el sarcasmo en expresión constructiva. Relación con Bach: Holly + Beech + Agrimony.',
    sintomas: ['sarcasmo', 'agresividad verbal', 'bruxismo', 'tensión mandibular', 'conflictos verbales constantes'] },
  { id: 'filaree', nombre: 'Filaree (Alfilerillo)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Para quienes se obsesionan con pequeños detalles cotidianos y pierden de vista el panorama general. Relación con Bach: Beech + Rock Water + White Chestnut.',
    sintomas: ['preocupación obsesiva por detalles', 'hiper-foco en minucias', 'ansiedad por orden y limpieza', 'estrés por nimiedades', 'se ahoga en un vaso de agua'] },
  { id: 'mountain-pride', nombre: 'Mountain Pride (Orgullo de la montaña)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Infunde valentía asertiva y energía guerrera para defender las propias convicciones. Relación con Bach: Centaury + Mimulus.',
    sintomas: ['vacilación ante el conflicto', 'retirada ante el desafío', 'falta de coraje moral', 'dificultad para poner límites firmes', 'evita confrontaciones'] },
  { id: 'pink-monkeyflower', nombre: 'Pink Monkeyflower (Mímulo rosado)', origen: 'California', categoria: 'Vida Social',
    descripcion: 'Ayuda a superar el miedo a la vulnerabilidad y la vergüenza de mostrar los sentimientos. Relación con Bach: Mimulus + Pine.',
    sintomas: ['miedo al rechazo', 'vergüenza de sentir', 'retraimiento por defensa', 'oculta su verdadero ser', 'secuelas de abuso'] },

  { id: 'buttercup', nombre: 'Buttercup (Botón de oro)', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Construye la autoestima y el reconocimiento del propio valor, para quienes se sienten insignificantes. Relación con Bach: Larch + Centaury + Pine.',
    sintomas: ['insignificancia', 'timidez extrema', 'desvalorización', 'comparación constante con otros', 'baja autoestima'] },
  { id: 'california-poppy', nombre: 'California Poppy (Amapola de California)', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Frena la búsqueda compulsiva de experiencias externas o el escapismo, anclando la paz en la experiencia interna. Relación con Bach: Clematis + Cerato + Agrimony.',
    sintomas: ['fascinación por lo externo', 'adicciones', 'escapismo', 'busca gurús o sustancias', 'dependencia de líderes espirituales'] },
  { id: 'self-heal', nombre: 'Self-Heal (Sanícula)', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Esencia maestra de la autocuración: despierta la responsabilidad y la capacidad innata de sanar. Relación con Bach: Gorse + Wild Rose.',
    sintomas: ['duda de poder sanar', 'dependencia excesiva de médicos', 'desánimo vital', 'se rinde ante enfermedad crónica', 'procesos de sanación lentos'] },
  { id: 'sunflower', nombre: 'Sunflower (Girasol)', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Equilibra el ego y sana la relación con la figura paterna, corrigiendo arrogancia o baja autoestima. Relación con Bach: Vine + Larch + Chicory.',
    sintomas: ['arrogancia', 'baja autoestima', 'conflicto con figura paterna', 'problemas de postura y columna', 'desequilibrio del ego'] },
  { id: 'zinnia', nombre: 'Zinnia', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Reconecta con el niño interior, el humor y la alegría, aliviando la rigidez por exceso de responsabilidad. Relación con Bach: Rock Water + Wild Rose + Oak.',
    sintomas: ['exceso de seriedad', 'amargura', 'falta de humor', 'rigidez vital', 'dificultad para jugar y divertirse'] },
  { id: 'california-wild-rose', nombre: 'California Wild Rose (Rosa de California)', origen: 'California', categoria: 'Autorrealización',
    descripcion: 'Restaura el entusiasmo y el compromiso con la vida, para la apatía profunda y la resignación pasiva. Relación con Bach: Wild Rose.',
    sintomas: ['apatía profunda', 'resignación pasiva', 'desgana existencial', 'falta de propósito', 'aburrimiento vital'] },

  { id: 'almond', nombre: 'Almond (Almendro)', origen: 'California', categoria: 'Grupo Especial y de Moderación',
    descripcion: 'Cultiva la templanza y el autocontrol frente a cualquier tipo de exceso. Relación con Bach: Cherry Plum + Rock Water + Vervain.',
    sintomas: ['tendencia a los excesos', 'compulsiones alimentarias', 'ansiedad por gratificación inmediata', 'falta de límites propios', 'estrés por hiperactividad'] },
  { id: 'fig-tree', nombre: 'Fig Tree (Higuera)', origen: 'California', categoria: 'Grupo Especial y de Moderación',
    descripcion: 'Disuelve sistemas de creencias rígidos, aportando flexibilidad ante las reglas y estructuras externas. Relación con Bach: Rock Water + Beech + Walnut.',
    sintomas: ['dogmatismo', 'rigidez de creencias', 'conflictos con la autoridad', 'rebelión autodestructiva', 'se siente encorsetado por normas'] },
  { id: 'hyssop', nombre: 'Hyssop (Hisopo)', origen: 'California', categoria: 'Grupo Especial y de Moderación',
    descripcion: 'Sana la autocondena y libera la culpa acumulada, permitiendo el perdón propio. Relación con Bach: Pine + Crab Apple.',
    sintomas: ['autocondena', 'autoflagelación', 'culpa punitiva', 'autorreproche', 'se castiga por errores del pasado'] },
  { id: 'lilac', nombre: 'Lilac (Lila)', origen: 'California', categoria: 'Grupo Especial y de Moderación',
    descripcion: 'Libera la postura y la columna de patrones familiares y transgeneracionales heredados. Relación con Bach: Rock Water + Willow + Walnut + Chestnut Bud.',
    sintomas: ['peso de mandatos familiares', 'rigidez en la columna', 'problemas de espalda crónicos', 'mandatos heredados', 'creencias familiares rígidas'] },
  { id: 'morning-glory', nombre: 'Morning Glory (Campanilla)', origen: 'California', categoria: 'Grupo Especial y de Moderación',
    descripcion: 'Restaura los ritmos circadianos naturales para quienes viven desfasados del ritmo solar. Relación con Bach: Hornbeam + Vervain + Wild Rose.',
    sintomas: ['letargo matutino', 'dependencia de cafeína', 'insomnio', 'desfase horario', 'estilo de vida nocturno'] },
];

/* Devuelve la lista completa de síntomas únicos, ordenada alfabéticamente,
   agrupados luego por categoría de la flor a la que pertenecen (para mostrar en checklist). */
function obtenerSintomasAgrupados() {
  const grupos = {};
  FLORES_DB.forEach(flor => {
    if (!grupos[flor.categoria]) grupos[flor.categoria] = new Set();
    flor.sintomas.forEach(s => grupos[flor.categoria].add(s));
  });
  const resultado = Object.keys(grupos).sort().map(categoria => ({
    categoria,
    sintomas: Array.from(grupos[categoria]).sort()
  }));
  return resultado;
}

/* Dado un array de síntomas seleccionados, devuelve las flores recomendadas
   ordenadas por cantidad de coincidencias (mayor primero). */
function recomendarFlores(sintomasSeleccionados) {
  if (!sintomasSeleccionados || sintomasSeleccionados.length === 0) return [];
  const resultados = FLORES_DB.map(flor => {
    const coincidencias = flor.sintomas.filter(s => sintomasSeleccionados.includes(s));
    return { flor, coincidencias: coincidencias.length };
  }).filter(r => r.coincidencias > 0);
  resultados.sort((a, b) => b.coincidencias - a.coincidencias);
  return resultados;
}

function buscarFlorPorNombre(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return FLORES_DB.filter(f => f.nombre.toLowerCase().includes(q));
}
