/* Base de datos de Flores de Bach y Esencias de California
   Cada flor tiene: id, nombre, origen (Bach/California), categoria emocional,
   descripcion corta y un array de sintomas/palabras clave para el recomendador. */

const FLORES_DB = [
  // ===================== FLORES DE BACH (38) =====================
  { id: 'agrimony', nombre: 'Agrimony (Agrimonia)', origen: 'Bach', categoria: 'Ansiedad y preocupación',
    descripcion: 'Para quienes ocultan su angustia detrás de una máscara de alegría y buen humor.',
    sintomas: ['oculta sus problemas', 'finge estar bien', 'evita conflictos', 'ansiedad oculta', 'busca aprobación', 'miedo a aburrir a otros con sus penas'] },
  { id: 'aspen', nombre: 'Aspen (Álamo temblón)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para miedos e inquietudes de origen desconocido, presentimientos vagos.',
    sintomas: ['miedo sin causa aparente', 'presentimientos', 'ansiedad nocturna', 'pesadillas', 'inquietud difusa', 'aprensión'] },
  { id: 'beech', nombre: 'Beech (Haya)', origen: 'Bach', categoria: 'Sensibilidad excesiva a las opiniones',
    descripcion: 'Para la intolerancia, la crítica excesiva y la falta de flexibilidad hacia los demás.',
    sintomas: ['intolerancia', 'critica a los demás', 'perfeccionismo con otros', 'rigidez', 'poca empatía', 'irritabilidad ante errores ajenos'] },
  { id: 'centaury', nombre: 'Centaury (Centaura)', origen: 'Bach', categoria: 'Falta de voluntad',
    descripcion: 'Para quienes no saben decir que no y se someten a la voluntad de otros.',
    sintomas: ['no puede decir que no', 'se somete a otros', 'falta de límites', 'complacencia excesiva', 'se deja explotar', 'baja autoafirmación'] },
  { id: 'cerato', nombre: 'Cerato (Ceratostigma)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para quienes dudan de su propio criterio y buscan constantemente la opinión de otros.',
    sintomas: ['duda de sí mismo', 'pide muchos consejos', 'inseguridad en decisiones', 'necesita validación externa', 'desconfía de su intuición'] },
  { id: 'cherry-plum', nombre: 'Cherry Plum (Ciruelo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el miedo a perder el control, a hacer algo impulsivo o dañino.',
    sintomas: ['miedo a perder el control', 'pensamientos impulsivos', 'miedo a hacerse daño', 'tensión extrema', 'explosiones de ira', 'colapso nervioso'] },
  { id: 'chestnut-bud', nombre: 'Chestnut Bud (Castaño de yemas)', origen: 'Bach', categoria: 'Falta de interés / aprendizaje',
    descripcion: 'Para quienes repiten los mismos errores sin aprender de la experiencia.',
    sintomas: ['repite los mismos errores', 'no aprende de la experiencia', 'distraído', 'falta de observación', 'apresurado'] },
  { id: 'chicory', nombre: 'Chicory (Achicoria)', origen: 'Bach', categoria: 'Sobreprotección / posesividad',
    descripcion: 'Para el amor posesivo, exigente, que necesita sentirse necesitado.',
    sintomas: ['posesivo', 'exigente con el cariño', 'manipulador emocional', 'necesita ser el centro de atención', 'autocompasión', 'controlador con los seres queridos'] },
  { id: 'clematis', nombre: 'Clematis (Clemátide)', origen: 'Bach', categoria: 'Falta de interés en el presente',
    descripcion: 'Para quienes viven en las nubes, soñadores, desconectados del presente.',
    sintomas: ['soñador', 'desconectado del presente', 'falta de concentración', 'somnolencia', 'evasión de la realidad', 'poca vitalidad'] },
  { id: 'crab-apple', nombre: 'Crab Apple (Manzano silvestre)', origen: 'Bach', categoria: 'Desánimo / purificación',
    descripcion: 'La flor de la limpieza, para sentimientos de suciedad física o mental, vergüenza corporal.',
    sintomas: ['sensación de suciedad', 'vergüenza del cuerpo', 'obsesión por los detalles', 'autocrítica física', 'necesidad de depurar', 'baja autoestima corporal'] },
  { id: 'elm', nombre: 'Elm (Olmo)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para quienes se sienten abrumados por la responsabilidad, agotados momentáneamente.',
    sintomas: ['abrumado por responsabilidades', 'agotamiento puntual', 'duda de su capacidad', 'sobrecarga laboral', 'estrés por exceso de tareas'] },
  { id: 'gentian', nombre: 'Gentian (Genciana)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el desánimo ante contratiempos, pesimismo con causa conocida.',
    sintomas: ['desánimo ante contratiempos', 'pesimismo', 'se rinde fácilmente', 'dudas tras un fracaso', 'desmotivación'] },
  { id: 'gorse', nombre: 'Gorse (Aulaga)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la desesperanza profunda, sensación de que nada puede ayudar.',
    sintomas: ['desesperanza', 'siente que nada ayudará', 'resignación', 'pesimismo extremo', 'falta de fe en la mejora'] },
  { id: 'heather', nombre: 'Heather (Brezo)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para quienes necesitan hablar constantemente de sí mismos y temen la soledad.',
    sintomas: ['habla solo de sí mismo', 'necesita compañía constante', 'miedo a la soledad', 'busca atención', 'ansiedad al estar solo'] },
  { id: 'holly', nombre: 'Holly (Acebo)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la ira, los celos, la envidia y la desconfianza.',
    sintomas: ['celos', 'envidia', 'ira', 'desconfianza', 'irritabilidad', 'rencor', 'agresividad'] },
  { id: 'honeysuckle', nombre: 'Honeysuckle (Madreselva)', origen: 'Bach', categoria: 'Falta de interés en el presente',
    descripcion: 'Para vivir anclado en recuerdos y añoranzas del pasado.',
    sintomas: ['vive en el pasado', 'nostalgia', 'añoranza', 'dificultad para avanzar', 'apego a recuerdos'] },
  { id: 'hornbeam', nombre: 'Hornbeam (Carpe)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la fatiga mental, el cansancio al pensar en las tareas diarias.',
    sintomas: ['cansancio mental', 'pereza matutina', 'falta de energía para empezar', 'agotamiento por rutina', 'procrastinación'] },
  { id: 'impatiens', nombre: 'Impatiens (Impaciencia)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para la impaciencia, la irritabilidad y las prisas.',
    sintomas: ['impaciencia', 'irritabilidad', 'prisa constante', 'tensión muscular', 'quiere hacer todo rápido', 'poca tolerancia a la lentitud ajena'] },
  { id: 'larch', nombre: 'Larch (Alerce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la falta de confianza en uno mismo, sensación de inferioridad.',
    sintomas: ['falta de confianza', 'sensación de inferioridad', 'miedo al fracaso', 'no se anima a intentar', 'autoestima baja'] },
  { id: 'mimulus', nombre: 'Mimulus (Mímulo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para miedos conocidos y concretos: a la oscuridad, a hablar en público, etc.',
    sintomas: ['miedo concreto', 'timidez', 'miedo a hablar en público', 'miedo a enfermedades', 'temores específicos', 'nerviosismo ante lo cotidiano'] },
  { id: 'mustard', nombre: 'Mustard (Mostaza)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la tristeza profunda que llega sin motivo aparente, como una nube negra.',
    sintomas: ['tristeza sin causa', 'melancolía', 'nube negra', 'depresión pasajera', 'cambios de humor repentinos'] },
  { id: 'oak', nombre: 'Oak (Roble)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para quienes luchan sin descanso a pesar del agotamiento, sin pedir ayuda.',
    sintomas: ['exceso de responsabilidad', 'no pide ayuda', 'lucha sin descanso', 'agotamiento por exigencia propia', 'perseverancia extrema'] },
  { id: 'olive', nombre: 'Olive (Olivo)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el agotamiento físico y mental extremo, tras un esfuerzo prolongado.',
    sintomas: ['agotamiento extremo', 'fatiga física', 'falta total de energía', 'convalecencia', 'exhausto tras esfuerzo prolongado'] },
  { id: 'pine', nombre: 'Pine (Pino)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la culpa excesiva, el autorreproche y el sentimiento de no merecer.',
    sintomas: ['culpa excesiva', 'autorreproche', 'se disculpa constantemente', 'no se siente merecedor', 'sentimiento de culpa ajena'] },
  { id: 'red-chestnut', nombre: 'Red Chestnut (Castaño rojo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el miedo y la preocupación excesiva por la seguridad de los seres queridos.',
    sintomas: ['preocupación excesiva por otros', 'miedo por la familia', 'anticipa desgracias ajenas', 'sobreprotección ansiosa'] },
  { id: 'rock-rose', nombre: 'Rock Rose (Heliantemo)', origen: 'Bach', categoria: 'Miedo',
    descripcion: 'Para el terror y el pánico agudo, situaciones de emergencia.',
    sintomas: ['terror', 'pánico', 'miedo extremo', 'pesadillas terroríficas', 'situación de emergencia', 'alarma'] },
  { id: 'rock-water', nombre: 'Rock Water (Agua de roca)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la rigidez consigo mismo, el autoexigencia extrema y el perfeccionismo.',
    sintomas: ['autoexigencia extrema', 'rigidez consigo mismo', 'perfeccionismo personal', 'autodisciplina excesiva', 'poca flexibilidad propia'] },
  { id: 'scleranthus', nombre: 'Scleranthus (Centinodia)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para la indecisión entre dos opciones y los cambios de humor bruscos.',
    sintomas: ['indecisión', 'cambios de humor bruscos', 'duda entre dos opciones', 'inestabilidad emocional', 'falta de equilibrio interior'] },
  { id: 'star-of-bethlehem', nombre: 'Star of Bethlehem (Estrella de Belén)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el shock, el trauma y las consecuencias de malas noticias.',
    sintomas: ['shock', 'trauma', 'duelo', 'mala noticia reciente', 'conmoción emocional', 'secuelas de un accidente'] },
  { id: 'sweet-chestnut', nombre: 'Sweet Chestnut (Castaño dulce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para la angustia extrema, sensación de haber llegado al límite de lo soportable.',
    sintomas: ['angustia extrema', 'límite de lo soportable', 'desesperación profunda', 'sensación de vacío total', 'noche oscura del alma'] },
  { id: 'vervain', nombre: 'Vervain (Verbena)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para el exceso de entusiasmo, fanatismo y tensión por querer convencer a otros.',
    sintomas: ['exceso de entusiasmo', 'fanatismo', 'quiere convencer a otros', 'tensión nerviosa', 'sobreesfuerzo por una causa', 'estrés por ideales'] },
  { id: 'vine', nombre: 'Vine (Vid)', origen: 'Bach', categoria: 'Sobreprotección',
    descripcion: 'Para la dominancia, el autoritarismo y la necesidad de controlar a otros.',
    sintomas: ['autoritario', 'dominante', 'necesita controlar a otros', 'inflexible con subordinados', 'ambición de poder'] },
  { id: 'walnut', nombre: 'Walnut (Nogal)', origen: 'Bach', categoria: 'Sensibilidad excesiva',
    descripcion: 'Para la protección en momentos de cambio y transición, para romper vínculos limitantes.',
    sintomas: ['dificultad con los cambios', 'transición vital', 'mudanza', 'nueva etapa', 'influencias externas', 'dejarse influenciar demasiado'] },
  { id: 'water-violet', nombre: 'Water Violet (Violeta de agua)', origen: 'Bach', categoria: 'Soledad',
    descripcion: 'Para quienes se aíslan por orgullo, prefieren la soledad y parecen distantes.',
    sintomas: ['aislamiento voluntario', 'orgullo', 'distante', 'prefiere estar solo', 'dificultad para pedir ayuda', 'reservado'] },
  { id: 'white-chestnut', nombre: 'White Chestnut (Castaño de indias)', origen: 'Bach', categoria: 'Falta de interés',
    descripcion: 'Para los pensamientos repetitivos e incontrolables, la mente que no descansa.',
    sintomas: ['pensamientos repetitivos', 'mente que no para', 'insomnio por pensar', 'rumiación mental', 'preocupaciones circulares'] },
  { id: 'wild-oat', nombre: 'Wild Oat (Avena silvestre)', origen: 'Bach', categoria: 'Incertidumbre',
    descripcion: 'Para la falta de dirección vital, no saber qué camino profesional o de vida seguir.',
    sintomas: ['falta de rumbo', 'no sabe qué hacer con su vida', 'indecisión vocacional', 'insatisfacción profesional', 'búsqueda de propósito'] },
  { id: 'wild-rose', nombre: 'Wild Rose (Rosa silvestre)', origen: 'Bach', categoria: 'Falta de interés',
    descripcion: 'Para la apatía y resignación, dejarse llevar sin motivación por la vida.',
    sintomas: ['apatía', 'resignación', 'falta de motivación', 'dejadez', 'monotonía sin queja', 'indiferencia'] },
  { id: 'willow', nombre: 'Willow (Sauce)', origen: 'Bach', categoria: 'Desánimo',
    descripcion: 'Para el resentimiento, la amargura y sentirse víctima de las circunstancias.',
    sintomas: ['resentimiento', 'amargura', 'sentirse víctima', 'autocompasión', 'rencor por injusticias', 'queja constante'] },
  { id: 'rescue-remedy', nombre: 'Rescue Remedy (Flor de rescate)', origen: 'Bach', categoria: 'Emergencia',
    descripcion: 'Combinación de emergencia para crisis agudas de estrés, pánico o shock puntual.',
    sintomas: ['crisis aguda', 'emergencia emocional', 'shock puntual', 'ataque de pánico', 'antes de un examen o evento estresante'] },

  // ===================== ESENCIAS DE CALIFORNIA (selección) =====================
  { id: 'baby-blue-eyes', nombre: 'Baby Blue Eyes', origen: 'California', categoria: 'Confianza y apertura',
    descripcion: 'Para recuperar la confianza e inocencia, sanar heridas con figuras de autoridad.',
    sintomas: ['desconfianza en figuras de autoridad', 'cinismo', 'dificultad para confiar', 'endurecimiento emocional', 'heridas de la infancia'] },
  { id: 'black-eyed-susan', nombre: 'Black-Eyed Susan', origen: 'California', categoria: 'Autoconocimiento',
    descripcion: 'Para integrar emociones reprimidas y mirar de frente lo que se evita.',
    sintomas: ['evita mirar sus emociones', 'niega sentimientos incómodos', 'represión emocional', 'necesita autoexploración profunda'] },
  { id: 'california-poppy', nombre: 'California Poppy (Amapola de California)', origen: 'California', categoria: 'Autenticidad',
    descripcion: 'Para dejar de buscar afuera lo que se debe encontrar en el propio interior.',
    sintomas: ['busca respuestas afuera', 'fascinación por lo místico ajeno', 'falta de luz interior propia', 'dependencia de gurús o sustancias'] },
  { id: 'canyon-dudleya', nombre: 'Canyon Dudleya', origen: 'California', categoria: 'Sensibilidad energética',
    descripcion: 'Para quienes absorben en exceso las energías del entorno y necesitan aterrizar.',
    sintomas: ['hipersensibilidad energética', 'absorbe emociones ajenas', 'dificultad para poner límites energéticos', 'sobrecarga sensorial'] },
  { id: 'fairy-lantern', nombre: 'Fairy Lantern', origen: 'California', categoria: 'Maduración',
    descripcion: 'Para asumir la propia madurez y responsabilidad adulta.',
    sintomas: ['dificultad para madurar', 'dependencia infantil', 'evita responsabilidades adultas', 'busca que lo cuiden'] },
  { id: 'fuchsia', nombre: 'Fuchsia', origen: 'California', categoria: 'Expresión emocional',
    descripcion: 'Para expresar emociones auténticas en lugar de reacciones exageradas o teatrales.',
    sintomas: ['emociones teatrales', 'reacciones exageradas', 'emociones reprimidas tras la fachada', 'histeria emocional'] },
  { id: 'golden-yarrow', nombre: 'Golden Yarrow', origen: 'California', categoria: 'Sensibilidad y protección',
    descripcion: 'Para quienes se aíslan por hipersensibilidad ante el mundo, especialmente en lo público.',
    sintomas: ['se aísla del grupo por sensibilidad', 'miedo escénico', 'ansiedad social', 'necesita protegerse sin perder la conexión'] },
  { id: 'mariposa-lily', nombre: 'Mariposa Lily', origen: 'California', categoria: 'Vínculo materno',
    descripcion: 'Para sanar la relación con la propia madre y el instinto de nutrir y ser nutrido.',
    sintomas: ['dificultad con el vínculo materno', 'frialdad afectiva', 'quiere sanar su maternidad', 'dificultad para nutrir emocionalmente'] },
  { id: 'pretty-face', nombre: 'Pretty Face', origen: 'California', categoria: 'Autoestima',
    descripcion: 'Para aceptar la propia belleza interior más allá de la apariencia física.',
    sintomas: ['obsesión con la apariencia', 'baja autoestima por el físico', 'no se siente atractivo', 'autocrítica estética'] },
  { id: 'pink-monkeyflower', nombre: 'Pink Monkeyflower', origen: 'California', categoria: 'Vulnerabilidad',
    descripcion: 'Para el miedo a mostrarse vulnerable y ser rechazado por lo que uno realmente es.',
    sintomas: ['miedo a ser vulnerable', 'miedo al rechazo', 'oculta su verdadero ser', 'vergüenza profunda'] },
  { id: 'sagebrush', nombre: 'Sagebrush', origen: 'California', categoria: 'Desapego',
    descripcion: 'Para soltar lo que ya no sirve e ir hacia la esencia de uno mismo.',
    sintomas: ['dificultad para soltar', 'apego a identidad antigua', 'necesita despojarse de lo superfluo', 'proceso de duelo por una etapa'] },
  { id: 'shooting-star', nombre: 'Shooting Star', origen: 'California', categoria: 'Pertenencia',
    descripcion: 'Para sentimientos profundos de no pertenecer a este mundo o a la propia familia.',
    sintomas: ['sensación de no pertenecer', 'desconexión con la tierra', 'sentirse extraño en el mundo', 'aislamiento existencial'] },
  { id: 'sunflower', nombre: 'Sunflower (Girasol)', origen: 'California', categoria: 'Identidad e individualidad',
    descripcion: 'Para equilibrar la relación con la propia identidad y la figura paterna.',
    sintomas: ['dificultad con la propia identidad', 'ego inflado o apagado', 'conflicto con figura paterna', 'necesita brillar con humildad'] },
  { id: 'trumpet-vine', nombre: 'Trumpet Vine', origen: 'California', categoria: 'Comunicación',
    descripcion: 'Para dar vitalidad y color a la expresión verbal, superar la timidez al hablar.',
    sintomas: ['habla monótona', 'dificultad para expresarse con fuerza', 'timidez al hablar en público', 'necesita expresividad'] },
  { id: 'yerba-santa', nombre: 'Yerba Santa', origen: 'California', categoria: 'Tristeza reprimida',
    descripcion: 'Para liberar la tristeza y el dolor emocional guardado en el pecho.',
    sintomas: ['tristeza reprimida', 'dolor emocional guardado', 'dificultad para llorar', 'opresión en el pecho', 'duelo no expresado'] },
  { id: 'zinnia', nombre: 'Zinnia', origen: 'California', categoria: 'Alegría y juego',
    descripcion: 'Para reconectar con el humor, el juego y la alegría espontánea de la vida.',
    sintomas: ['exceso de seriedad', 'falta de humor', 'dificultad para jugar y divertirse', 'vida demasiado rígida'] },
];

/* Devuelve la lista completa de síntomas únicos, ordenada alfabéticamente,
   agrupados luego por categoría de la flor a la que pertenecen (para mostrar en checklist). */
function obtenerSintomasAgrupados() {
  const grupos = {};
  FLORES_DB.forEach(flor => {
    if (!grupos[flor.categoria]) grupos[flor.categoria] = new Set();
    flor.sintomas.forEach(s => grupos[flor.categoria].add(s));
  });
  const resultado = Object.keys(grupos).sort().map(categoria => ({
    categoria,
    sintomas: Array.from(grupos[categoria]).sort()
  }));
  return resultado;
}

/* Dado un array de síntomas seleccionados, devuelve las flores recomendadas
   ordenadas por cantidad de coincidencias (mayor primero). */
function recomendarFlores(sintomasSeleccionados) {
  if (!sintomasSeleccionados || sintomasSeleccionados.length === 0) return [];
  const resultados = FLORES_DB.map(flor => {
    const coincidencias = flor.sintomas.filter(s => sintomasSeleccionados.includes(s));
    return { flor, coincidencias: coincidencias.length };
  }).filter(r => r.coincidencias > 0);
  resultados.sort((a, b) => b.coincidencias - a.coincidencias);
  return resultados;
}

function buscarFlorPorNombre(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return FLORES_DB.filter(f => f.nombre.toLowerCase().includes(q));
}
